import logging

class EarlyStop(Exception):
    """Empty class used to capture early user temination of the model. Allows exit to be captured such that
    clean-up operations to be performed."""
    pass


def close_loggers(logger):
    """ Safely closes the logs being generated by logging."""
    handlers = logger.handlers[:]
    for handler in handlers:
        handler.close()
        logger.removeHandler(handler)

def printhead(msg):
    """ Prints `msg` as a heading in the output
    Args:
        msg: str - the message to be printed
    """
    separator = '-------------------------'
    logging.info(separator)
    logging.info('[*] ' + msg)
    logging.info(separator)
    return